#!/bin/sh
# To setup git hooks run:
#   > git config core.hooksPath .git-hooks || echo 'Not in a git repo'
echo "Running pre-commit hook from .git-hooks/pre-commit..."
nginx -t -c ~/projects/sneat/sneat-devenv/nginx-conf/nginx.conf
